import type { HookEventName } from "./types.ts";

export const LIVE_EVENT_BINDINGS = {
  SessionStart: "pi:session_start",
  Setup: "pi flags:init-only|init|maintenance",
  UserPromptSubmit: "pi:input",
  UserPromptExpansion: "pi:input slash-command expansion",
  PreToolUse: "pi:tool_call",
  PermissionRequest: "intentionally ignored: choco-pi has no permission system",
  PermissionDenied: "intentionally ignored: choco-pi has no permission system",
  PostToolUse: "pi:tool_result success",
  PostToolUseFailure: "pi:tool_result failure",
  PostToolBatch: "pi:turn_end",
  Notification: "permission/idle/subagent timers and events",
  MessageDisplay: "pi:message_update plus markdown transformer",
  SubagentStart: "subagents:started",
  SubagentStop: "subagents:completed|failed",
  TaskCreated: "TaskCreate tool",
  TaskCompleted: "TaskUpdate and workflow completion",
  Stop: "pi:agent_end",
  StopFailure: "pi:agent_end error",
  TeammateIdle: "subagent settlement",
  InstructionsLoaded: "pi:before_agent_start contextFiles",
  ConfigChange: "settings/skills filesystem watcher",
  CwdChanged: "extension context cwd transition",
  DirectoryAdded: "/add-dir and register_repo_root event bridge",
  FileChanged: "literal/dynamic filesystem watcher",
  WorktreeCreate: "Agent PreToolUse isolation bridge",
  WorktreeRemove: "subagent hook-managed worktree settlement",
  PreCompact: "pi:session_before_compact",
  PostCompact: "pi:session_compact",
  Elicitation: "MCP elicitation request bridge",
  ElicitationResult: "MCP elicitation response bridge",
  SessionEnd: "pi:session_shutdown",
} as const satisfies Record<HookEventName, string>;
