import assert from "node:assert/strict";
import test from "node:test";
import { assessDiff } from "../.pi/extensions/review/core/heuristics.ts";
import type {
	DiffFile,
	DiffHunk,
	DiffLine,
	DiffModel,
	ResolvedReviewConfig,
} from "../.pi/extensions/review/core/types.ts";

const baseConfig: ResolvedReviewConfig = {
	editor: { command: ["true"], mode: "terminal" },
	highlight: { enabled: true, maxFileBytes: 1, maxDiffLines: 1 },
	heuristics: { riskPatterns: [], collapsePatterns: [] },
};

function hunk(id: string, lines: DiffLine[]): DiffHunk {
	return { id, header: "@@ -1 +1 @@", oldStart: 1, oldLines: 1, newStart: 1, newLines: 1, lines };
}

function file(path: string, overrides: Partial<DiffFile> = {}): DiffFile {
	return {
		path,
		kind: "modified",
		hunks: [hunk(`${path}:hunk`, [
			{ kind: "del", oldLine: 1, text: "old" },
			{ kind: "add", newLine: 1, text: "new" },
		])],
		additions: 1,
		deletions: 1,
		...overrides,
	};
}

function model(files: DiffFile[]): DiffModel {
	return { baseSha: "base", headSha: "head", files };
}

function assessmentFor(files: DiffFile[], path: string, config = baseConfig) {
	const result = assessDiff(model(files), config);
	const assessment = result.files.find((candidate) => candidate.path === path);
	assert.ok(assessment, `missing assessment for ${path}`);
	return assessment;
}

test("built-in noise rules collapse lockfiles, generated files, bundles, vendor output, snapshots, binaries, and rename-only changes", () => {
	const generated = file("src/client.ts", {
		hunks: [hunk("generated", [
			{ kind: "context", oldLine: 1, newLine: 1, text: "// Code generated by schema; DO NOT EDIT." },
			{ kind: "del", oldLine: 2, text: "old" },
			{ kind: "add", newLine: 2, text: "new" },
		])],
	});
	const files = [
		file("pnpm-lock.yaml"),
		generated,
		file("public/app.min.js"),
		file("vendor/library/index.js"),
		file("dist/app.js"),
		file("src/__snapshots__/view.test.ts.snap"),
		file("assets/logo.png", { kind: "binary", hunks: [], additions: 0, deletions: 0 }),
		file("src/new-name.ts", { kind: "renamed", oldPath: "src/old-name.ts", hunks: [], additions: 0, deletions: 0 }),
	];

	const result = assessDiff(model(files), baseConfig);
	for (const assessment of result.files) {
		assert.equal(assessment.collapsed, true, assessment.path);
		assert.ok(assessment.collapseReason, assessment.path);
	}
	assert.match(result.files[0].collapseReason ?? "", /lockfile/i);
	assert.match(result.files[1].collapseReason ?? "", /generated-code header/i);
	assert.match(result.files[2].collapseReason ?? "", /minified bundle/i);
	assert.match(result.files[6].collapseReason ?? "", /no reviewable text/i);
	assert.match(result.files[7].collapseReason ?? "", /rename-only/i);
});

test("format-only hunks fold in brace languages but remain visible where whitespace can be semantic", () => {
	const typescript = file("src/view.ts", {
		hunks: [hunk("ts-format", [
			{ kind: "del", oldLine: 1, text: "if (ready) {  run(); }" },
			{ kind: "add", newLine: 1, text: "if (ready) { run(); }" },
		])],
	});
	const python = file("src/view.py", {
		hunks: [hunk("py-indent", [
			{ kind: "del", oldLine: 1, text: "  run()" },
			{ kind: "add", newLine: 1, text: "    run()" },
		])],
	});
	const stringData = file("src/message.ts", {
		hunks: [hunk("string-data", [
			{ kind: "del", oldLine: 1, text: "const message = 'two  spaces';" },
			{ kind: "add", newLine: 1, text: "const message = 'two spaces';" },
		])],
	});

	const result = assessDiff(model([typescript, python, stringData]), baseConfig);
	assert.deepEqual(result.hunks[0], {
		hunkId: "ts-format",
		collapsed: true,
		reason: "Added and removed text differs only by normalized whitespace",
	});
	assert.deepEqual(result.hunks[1], { hunkId: "py-indent", collapsed: false });
	assert.deepEqual(result.hunks[2], { hunkId: "string-data", collapsed: false });
	assert.equal(result.files[0].collapsed, true);
	assert.equal(result.files[1].collapsed, false);
	assert.equal(result.files[2].collapsed, false);
});

test("each built-in risk signal contributes a specific reason", () => {
	const files = [
		file("src/auth/permissions.ts"),
		file("src/crypto/secrets.ts"),
		file("db/migrations/001_schema.sql"),
		file("src/payments/billing.ts"),
		file("tests/account.test.ts", { kind: "deleted", additions: 0, deletions: 30 }),
		file("package.json"),
		file(".github/workflows/ci.yml"),
		file("src/obsolete.ts", { additions: 5, deletions: 500 }),
	];
	const result = assessDiff(model(files), baseConfig);
	const reasons = result.files.map((assessment) => assessment.reasons.join("\n"));

	assert.match(reasons[0], /Authentication, authorization, or permission/);
	assert.match(reasons[1], /Cryptography or secret-handling/);
	assert.match(reasons[2], /Database migration or schema/);
	assert.match(reasons[3], /Payment or billing/);
	assert.match(reasons[4], /Test file was deleted/);
	assert.match(reasons[5], /Dependency manifest/);
	assert.match(reasons[6], /CI, container, or environment configuration/);
	assert.match(reasons[7], /Unusually large deletion \(500 lines removed\)/);
	for (const assessment of result.files) assert.ok(assessment.riskScore > 0, assessment.path);

	const emptied = assessmentFor([
		file("tests/empty.spec.ts", { additions: 0, deletions: 12 }),
	], "tests/empty.spec.ts");
	assert.match(emptied.reasons.join("\n"), /Test file may have been emptied/);
});

test("risk reasons are cumulative and risky files override ordinary collapse rules", () => {
	const riskyGenerated = file("dist/auth/secrets.ts", {
		hunks: [hunk("risky-generated", [
			{ kind: "context", oldLine: 1, newLine: 1, text: "// @generated" },
			{ kind: "del", oldLine: 2, text: "old credential" },
			{ kind: "add", newLine: 2, text: "new credential" },
		])],
	});

	const assessment = assessmentFor([riskyGenerated], riskyGenerated.path);
	assert.equal(assessment.collapsed, false);
	assert.equal(assessment.reasons.length, 2);
	assert.ok(assessment.reasons.some((reason) => reason.includes("Authentication")));
	assert.ok(assessment.reasons.some((reason) => reason.includes("secret-handling")));
});

test("review order is descending by risk and preserves input order for equal scores", () => {
	const files = [
		file("src/plain-first.ts"),
		file("src/auth/first.ts"),
		file("src/plain-second.ts"),
		file("src/auth/second.ts"),
	];

	const first = assessDiff(model(files), baseConfig).reviewOrder;
	const second = assessDiff(model(files), baseConfig).reviewOrder;
	assert.deepEqual(first, [
		"src/auth/first.ts",
		"src/auth/second.ts",
		"src/plain-first.ts",
		"src/plain-second.ts",
	]);
	assert.deepEqual(second, first);
});

test("user path substrings extend built-in risk and collapse rules", () => {
	const config: ResolvedReviewConfig = {
		...baseConfig,
		heuristics: { riskPatterns: ["Critical/"], collapsePatterns: ["fixtures/recordings"] },
	};
	const files = [
		file("src/Critical/handler.ts"),
		file("tests/fixtures/recordings/http.json"),
		file("pnpm-lock.yaml"),
		file("src/auth/login.ts"),
	];
	const result = assessDiff(model(files), config);

	assert.match(result.files[0].reasons.join("\n"), /Matched user risk pattern: Critical\//);
	assert.equal(result.files[1].collapsed, true);
	assert.match(result.files[1].collapseReason ?? "", /Matched user collapse pattern: fixtures\/recordings/);
	assert.equal(result.files[2].collapsed, true, "built-in lockfile rule remains active");
	assert.match(result.files[2].collapseReason ?? "", /lockfile/i);
	assert.match(result.files[3].reasons.join("\n"), /Authentication/);
});
